'use strict';
const fs     = require('fs');
const path   = require('path');
const crypto = require('crypto');

const MAIN_CPP = [
  '#include <SFML/Graphics.hpp>',
  '#include <optional>',
  '',
  'int main() {',
  '    sf::RenderWindow window(sf::VideoMode({800u, 600u}), "SFML Project");',
  '    window.setFramerateLimit(60);',
  '',
  '    while (window.isOpen()) {',
  '        while (const std::optional event = window.pollEvent()) {',
  '            if (event->is<sf::Event::Closed>())',
  '                window.close();',
  '        }',
  '',
  '        window.clear(sf::Color::Black);',
  '        window.display();',
  '    }',
  '    return 0;',
  '}',
].join('\n');

function guid() { return crypto.randomUUID().toUpperCase(); }
function safeNamespace(name) { return name.replace(/[^\w]+/g, '') || 'SFMLProject'; }

// ── ma-sfml.props ─────────────────────────────────────────────────────────────
// Uses the ABSOLUTE path of the SFML directory so the props file can live
// anywhere and still resolve correctly — no $(SolutionDir) guesswork needed.
function propsContent(sfmlPath) {
  const s = sfmlPath.replace(/\//g, '\\');
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by ma-sfml — do not edit manually. -->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup Label="ma-sfml">
    <SfmlDir>${s}</SfmlDir>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(SfmlDir)\\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(SfmlDir)\\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies Condition="'$(Configuration)'=='Debug'"
        >sfml-graphics-d.lib;sfml-window-d.lib;sfml-system-d.lib;sfml-audio-d.lib;sfml-network-d.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalDependencies Condition="'$(Configuration)'!='Debug'"
        >sfml-graphics.lib;sfml-window.lib;sfml-system.lib;sfml-audio.lib;sfml-network.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
    <PostBuildEvent>
      <!-- Copy SFML DLLs to output folder so the .exe finds them at runtime -->
      <Command>xcopy /Y /I "$(SfmlDir)\\bin\\*.dll" "$(OutDir)"</Command>
      <Message>Copying SFML DLLs to output directory</Message>
    </PostBuildEvent>
  </ItemDefinitionGroup>

</Project>
`;
}

// ── Minimal .vcxproj (VS 2022 / v143 toolset) ─────────────────────────────────
function vcxprojContent(projName, projGuid, propsRelPath) {
  return `<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration><Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration><Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <VCProjectVersion>17.0</VCProjectVersion>
    <ProjectGuid>{${projGuid}}</ProjectGuid>
    <RootNamespace>${safeNamespace(projName)}</RootNamespace>
    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>v143</PlatformToolset>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>v143</PlatformToolset>
    <WholeProgramOptimization>true</WholeProgramOptimization>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings" />
  <ImportGroup Label="Shared" />
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Import Project="$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props"
            Condition="exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')"
            Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Import Project="$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props"
            Condition="exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')"
            Label="LocalAppDataPlatform" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <PreprocessorDefinitions>_DEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <LanguageStandard>stdcpp20</LanguageStandard>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <PreprocessorDefinitions>NDEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <LanguageStandard>stdcpp20</LanguageStandard>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="src\\main.cpp" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets" />
  <!-- ma-sfml: SFML include, lib, and DLL paths -->
  <Import Project="${propsRelPath}" />
</Project>
`;
}

function slnContent(projName, projGuid) {
  return `
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.0.31903.59
MinimumVisualStudioVersion = 10.0.40219.1
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "${projName}", "${projName}.vcxproj", "{${projGuid}}"
EndProject
Global
\tGlobalSection(SolutionConfigurationPlatforms) = preSolution
\t\tDebug|x64 = Debug|x64
\t\tRelease|x64 = Release|x64
\tEndGlobalSection
\tGlobalSection(ProjectConfigurationPlatforms) = postSolution
\t\t{${projGuid}}.Debug|x64.ActiveCfg = Debug|x64
\t\t{${projGuid}}.Debug|x64.Build.0 = Debug|x64
\t\t{${projGuid}}.Release|x64.ActiveCfg = Release|x64
\t\t{${projGuid}}.Release|x64.Build.0 = Release|x64
\tEndGlobalSection
\tGlobalSection(SolutionProperties) = preSolution
\t\tHideSolutionNode = FALSE
\tEndGlobalSection
EndGlobal
`;
}

// ── Inject <Import> into existing .vcxproj ────────────────────────────────────
function injectPropsImport(vcxFile, propsAbsPath) {
  try {
    let content = fs.readFileSync(vcxFile, 'utf8');
    if (content.includes('ma-sfml.props')) {
      // Already injected — just update the path in case SFML moved
      content = content.replace(/<Import Project="[^"]*ma-sfml\.props"[^/]*\/>/,
        `<Import Project="${propsAbsPath.replace(/\\/g, '\\\\')}" />`);
    } else {
      // Use the ABSOLUTE path so VS can always find it regardless of folder structure
      content = content.replace('</Project>',
        `  <!-- ma-sfml: SFML include, lib, and DLL paths -->\n  <Import Project="${propsAbsPath.replace(/\\/g, '\\\\')}" />\n</Project>`);
    }
    fs.writeFileSync(vcxFile, content, 'utf8');
  } catch (e) {
    throw new Error('Could not update .vcxproj: ' + e.message);
  }
}

// ── Main export ───────────────────────────────────────────────────────────────
module.exports = function linkVs(projectDir, sfmlPath, projectName, opts = {}) {
  const { createProject = false, vcxprojPath = null } = opts;
  const files = [];

  if (createProject) {
    // New project — vcxproj and props both live in projectDir
    const projGuid  = guid();
    const propsFile = path.join(projectDir, 'ma-sfml.props');
    const vcxFile   = path.join(projectDir, `${projectName}.vcxproj`);
    const slnFile   = path.join(projectDir, `${projectName}.sln`);
    const srcDir    = path.join(projectDir, 'src');

    fs.writeFileSync(propsFile, propsContent(sfmlPath), 'utf8');
    fs.writeFileSync(vcxFile, vcxprojContent(projectName, projGuid, 'ma-sfml.props'), 'utf8');
    fs.writeFileSync(slnFile, slnContent(projectName, projGuid), 'utf8');

    if (!fs.existsSync(srcDir)) fs.mkdirSync(srcDir, { recursive: true });
    const mainCpp = path.join(srcDir, 'main.cpp');
    if (!fs.existsSync(mainCpp)) fs.writeFileSync(mainCpp, MAIN_CPP, 'utf8');

    files.push('ma-sfml.props', `${projectName}.vcxproj`, `${projectName}.sln`, 'src/main.cpp');

    return {
      files,
      manifest: {
        ide: 'vs',
        propsFile,
        vcxprojPath: vcxFile,
        configFiles: ['ma-sfml.props', `${projectName}.vcxproj`, `${projectName}.sln`],
        stub: 'src/main.cpp',
      },
    };

  } else if (vcxprojPath) {
    // Existing project — place props NEXT TO the .vcxproj (same directory)
    // Then inject the ABSOLUTE path into the .vcxproj so VS always finds it,
    // regardless of how deep the .vcxproj is nested relative to the .sln.
    const vcxDir    = path.dirname(vcxprojPath);
    const propsFile = path.join(vcxDir, 'ma-sfml.props');

    fs.writeFileSync(propsFile, propsContent(sfmlPath), 'utf8');
    injectPropsImport(vcxprojPath, propsFile);

    files.push(
      path.relative(projectDir, propsFile).replace(/\\/g, '/') + '  (created)',
      path.relative(projectDir, vcxprojPath).replace(/\\/g, '/') + '  (updated)',
    );

    return {
      files,
      manifest: {
        ide: 'vs',
        propsFile,
        vcxprojPath,
        configFiles: [path.relative(projectDir, propsFile).replace(/\\/g, '/')],
        stub: null,
      },
    };

  } else {
    throw new Error('No .vcxproj found. Run from inside your Visual Studio project folder.');
  }
};
